version: '3.7'
services:

  mysql:
    image: mysql:8 # https://github.com/docker-library/mysql/blob/696fc899126ae00771b5d87bdadae836e704ae7d/8.0/Dockerfile
    container_name: example_mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT_EXTERNAL}:3306'
    volumes:
      - mysql-data:/var/lib/mysql # https://github.com/docker-library/mysql/blob/696fc899126ae00771b5d87bdadae836e704ae7d/8.0/Dockerfile#L67
      - ./resources/docker/mysql/configs/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    command:
      - "--default-authentication-plugin=mysql_native_password"


  nginx:
    image: nginx:alpine
    container_name: example_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www
      - ./resources/docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - php
      - mysql
    links:
      - php

  php:
    build:
      args:
        user: nebvlad
        uid: 1000
      context: .
      dockerfile: ./resources/docker/php/Dockerfile
    container_name:  example_php
    volumes:
      - .:/var/www
      - ./resources/docker/php/configs/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini:ro
      - ./resources/docker/php/configs/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./resources/docker/php/configs/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    links:
      - mysql
    depends_on:
      - mysql

volumes:
  mysql-data:
